directories:
  output: builder
  buildResources: build
appId: com.wss.app
win:
  target:
    - nsis
    - zip
mac:
  category: hbgj.electron.hbgj
  target:
    - zip
    - dmg
files:
  - filter:
      - build/**/*
      - main.js
      - preload.js
electronVersion: 9.2.1
